require('dotenv').config();
const path=require('path'),fs=require('fs'),crypto=require('crypto');
const express=require('express'),cookieSession=require('cookie-session'),helmet=require('helmet'),multer=require('multer');
const QRCode=require('qrcode'),{parse}=require('csv-parse/sync'),XLSX=require('xlsx'),{PDFDocument,StandardFonts,rgb}=require('pdf-lib');
const {createClient}=require('@supabase/supabase-js'),{google}=require('googleapis'),{Readable}=require('stream');
const app=express(),ROOT=__dirname,TMP=process.env.VERCEL?path.join('/tmp','dpea-imports'):path.join(ROOT,'storage','imports');fs.mkdirSync(TMP,{recursive:true});
const upload=multer({dest:TMP,limits:{fileSize:10e6},fileFilter:(_r,f,cb)=>cb(null,/\.(csv|xlsx)$/i.test(f.originalname))});
const templateUpload=multer({storage:multer.memoryStorage(),limits:{fileSize:15e6},fileFilter:(_r,f,cb)=>cb(null,/^image\/(png|jpeg)$/.test(f.mimetype))});
const signatureUpload=multer({storage:multer.memoryStorage(),limits:{fileSize:3e6},fileFilter:(_r,f,cb)=>cb(null,f.mimetype==='image/png')});
const env=n=>{if(!process.env[n])throw Error(`Falta la variable ${n}`);return process.env[n]};
const clean=(v,n=500)=>String(v??'').trim().slice(0,n);
const code=()=>`DPEA-${new Date().getFullYear()}-${crypto.randomBytes(6).toString('hex').toUpperCase()}`;
const verificationLink=(base,certificateCode)=>{const endpoint=clean(process.env.OFFICIAL_VERIFY_URL,500);return endpoint?`${endpoint}${endpoint.includes('?')?'&':'?'}codigo=${encodeURIComponent(certificateCode)}`:`${base}/verificar/${encodeURIComponent(certificateCode)}`};
const db=()=>createClient(env('SUPABASE_URL'),env('SUPABASE_SERVICE_ROLE_KEY'),{auth:{persistSession:false}});
const oauth=()=>new google.auth.OAuth2(env('GOOGLE_CLIENT_ID'),env('GOOGLE_CLIENT_SECRET'),env('GOOGLE_CALLBACK_URL'));
async function googleAuth(){const auth=oauth();let token=process.env.GOOGLE_REFRESH_TOKEN;if(!token){const{data,error}=await db().from('integration_settings').select('value').eq('key','google_refresh_token').maybeSingle();if(error)throw error;token=data?.value}if(!token)throw Error('Google no está conectado. Use el botón Conectar Google del panel.');auth.setCredentials({refresh_token:token});return auth}
async function gd(){return google.drive({version:'v3',auth:await googleAuth()})}
async function gs(){return google.sheets({version:'v4',auth:await googleAuth()})}
app.set('view engine','ejs');app.set('views',path.join(ROOT,'views'));app.set('trust proxy',1);
app.use(helmet({contentSecurityPolicy:false}),express.urlencoded({extended:false}),express.json(),express.static(path.join(ROOT,'public')));
app.use(cookieSession({name:'dpea_session',keys:[process.env.SESSION_SECRET||'cambiar'],httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:28800000}));
app.use((req,res,next)=>{res.locals.institution=process.env.INSTITUTION_NAME||'Departamento de Planificación y Evaluación Académica';res.locals.officialUrl=process.env.OFFICIAL_URL||'https://planificacionacademica.usfx.bo/';res.locals.baseUrl=(process.env.BASE_URL||`${req.protocol}://${req.get('host')}`).replace(/\/$/,'');res.locals.user=req.session?.user||null;res.locals.message=req.session?.message||null;if(req.session)delete req.session.message;next()});
const auth=(req,res,next)=>req.session?.user?next():res.redirect('/admin/login');
app.get('/admin/google/conectar',auth,(req,res)=>{const state=crypto.randomBytes(24).toString('hex');req.session.googleState=state;res.redirect(oauth().generateAuthUrl({access_type:'offline',prompt:'consent',scope:['https://www.googleapis.com/auth/drive','https://www.googleapis.com/auth/spreadsheets'],state}))});
app.get('/auth/google/callback',async(req,res,next)=>{try{if(!req.session?.user||!req.query.state||req.query.state!==req.session.googleState)throw Error('Solicitud de conexión inválida.');delete req.session.googleState;const{tokens}=await oauth().getToken(clean(req.query.code,500));if(!tokens.refresh_token)throw Error('Google no entregó refresh_token. Vuelva a conectar y acepte los permisos.');const{error}=await db().from('integration_settings').upsert({key:'google_refresh_token',value:tokens.refresh_token},{onConflict:'key'});if(error)throw error;req.session.message='Google Drive y Google Sheets conectados correctamente.';res.redirect('/admin')}catch(e){next(e)}});
async function courseMeta(id){try{const saved=await setting(`course_config_${id}`);return saved?JSON.parse(saved):{signatures:[]}}catch(e){console.warn('No se pudo leer la configuración del curso:',e.message);return{signatures:[]}}}
async function saveCourseMeta(id,meta){await saveSetting(`course_config_${id}`,JSON.stringify(meta))}
async function withCourseMeta(c){return c?{...c,...await courseMeta(c.id)}:c}
async function courses(){const{data,error}=await db().from('courses').select('*').order('title');if(error)throw error;return Promise.all((data||[]).map(withCourseMeta))}
async function findCourse(title){const{data,error}=await db().from('courses').select('*').ilike('title',clean(title,250)).maybeSingle();if(error)throw error;return withCourseMeta(data)}
async function course(title,description='',templateFileId='',templateName='',endDate='',updateTemplate=false,courseSignatures=null){title=clean(title,250);description=clean(description,2500);templateFileId=clean(templateFileId,250);templateName=clean(templateName,250);endDate=clean(endDate,30);if(!title)throw Error('El curso es obligatorio');const client=db();let{data,error}=await client.from('courses').select('*').ilike('title',title).maybeSingle();if(error)throw error;if(data){const changes={};if(description&&description!==data.description)changes.description=description;if(Object.keys(changes).length){({data,error}=await client.from('courses').update(changes).eq('id',data.id).select().single());if(error)throw error}const meta=await courseMeta(data.id);if(endDate)meta.end_date=endDate;if(updateTemplate){meta.template_file_id=templateFileId||null;meta.template_name=templateName||null}if(courseSignatures!==null)meta.signatures=courseSignatures;await saveCourseMeta(data.id,meta);return{...data,...meta}}({data,error}=await client.from('courses').insert({title,description}).select().single());if(error)throw error;const meta={end_date:endDate||null,template_file_id:templateFileId||null,template_name:templateName||null,signatures:courseSignatures||[]};await saveCourseMeta(data.id,meta);return{...data,...meta}}
async function folder(c){if(c.drive_folder_id)return c.drive_folder_id;const api=await gd(),root=env('GOOGLE_DRIVE_ROOT_FOLDER_ID'),name=clean(c.title,100).replace(/[\\/:*?"<>|]/g,'-'),q=name.replace(/'/g,"\\'");const found=await api.files.list({q:`'${root}' in parents and name='${q}' and mimeType='application/vnd.google-apps.folder' and trashed=false`,fields:'files(id)',supportsAllDrives:true,includeItemsFromAllDrives:true});let id=found.data.files?.[0]?.id;if(!id)id=(await api.files.create({requestBody:{name,mimeType:'application/vnd.google-apps.folder',parents:[root]},fields:'id',supportsAllDrives:true})).data.id;const{error}=await db().from('courses').update({drive_folder_id:id}).eq('id',c.id);if(error)throw error;c.drive_folder_id=id;return id}
async function templatesFolder(){const api=await gd(),root=env('GOOGLE_DRIVE_ROOT_FOLDER_ID'),name='_PLANTILLAS';const found=await api.files.list({q:`'${root}' in parents and name='${name}' and mimeType='application/vnd.google-apps.folder' and trashed=false`,fields:'files(id)',supportsAllDrives:true,includeItemsFromAllDrives:true});return found.data.files?.[0]?.id||(await api.files.create({requestBody:{name,mimeType:'application/vnd.google-apps.folder',parents:[root]},fields:'id',supportsAllDrives:true})).data.id}
async function signaturesFolder(){const api=await gd(),root=env('GOOGLE_DRIVE_ROOT_FOLDER_ID'),name='_FIRMAS';const found=await api.files.list({q:`'${root}' in parents and name='${name}' and mimeType='application/vnd.google-apps.folder' and trashed=false`,fields:'files(id)',supportsAllDrives:true,includeItemsFromAllDrives:true});return found.data.files?.[0]?.id||(await api.files.create({requestBody:{name,mimeType:'application/vnd.google-apps.folder',parents:[root]},fields:'id',supportsAllDrives:true})).data.id}
async function templates(){const api=await gd(),parent=await templatesFolder(),result=await api.files.list({q:`'${parent}' in parents and (mimeType='image/png' or mimeType='image/jpeg') and trashed=false`,fields:'files(id,name,mimeType,webViewLink)',orderBy:'name',supportsAllDrives:true,includeItemsFromAllDrives:true});return result.data.files||[]}
async function safeTemplates(){try{return await templates()}catch(e){console.warn('No se pudieron listar plantillas:',e.message);return[]}}
async function templateBuffer(fileId){if(!fileId)return null;try{const result=await (await gd()).files.get({fileId,alt:'media',supportsAllDrives:true},{responseType:'arraybuffer'});return Buffer.from(result.data)}catch(e){console.warn(`No se pudo leer el archivo de Drive ${fileId}:`,e.message);return null}}
async function setting(key){const{data,error}=await db().from('integration_settings').select('value').eq('key',key).maybeSingle();if(error)throw error;return data?.value||null}
async function saveSetting(key,value){const{error}=await db().from('integration_settings').upsert({key,value},{onConflict:'key'});if(error)throw error}
async function activity(req,action,details={}){try{const{error}=await db().from('activity_log').insert({actor:clean(req.session?.user||'administrador',120),action:clean(action,120),details});if(error)throw error}catch(e){console.warn('No se pudo registrar la actividad:',e.message)}}
async function trashDriveFile(fileId){if(!fileId)return;await (await gd()).files.update({fileId,requestBody:{trashed:true},supportsAllDrives:true})}
async function signatures(){try{const saved=await setting('certificate_signatures');return saved?JSON.parse(saved):[]}catch(e){console.warn('No se pudieron leer las firmas:',e.message);return[]}}
async function signatureAssets(list=[]){return Promise.all((list||[]).filter(s=>s.file_id).slice(0,5).map(async s=>({...s,image:await templateBuffer(s.file_id)})))}
async function buildCourseSignatures(req,current=[]){const updated=[],files=req.files||{};let api=null;for(let i=1;i<=5;i++){const old=current[i-1]||{},file=files[`firma_${i}`]?.[0];if(req.body[`eliminar_firma_${i}`]==='1'){await trashDriveFile(old.file_id);await activity(req,'Firma eliminada',{position:i,file_id:old.file_id});continue}let fileId=old.file_id;if(file){api??=await gd();if(old.file_id)await trashDriveFile(old.file_id);fileId=(await api.files.create({requestBody:{name:`firma-curso-${i}-${clean(file.originalname,150)}`,parents:[await signaturesFolder()]},media:{mimeType:'image/png',body:Readable.from(file.buffer)},fields:'id',supportsAllDrives:true})).data.id}const item={file_id:fileId,name:clean(req.body[`nombre_firma_${i}`]||old.name,120),role:clean(req.body[`cargo_firma_${i}`]||old.role,160),institution:clean(req.body[`institucion_firma_${i}`]||old.institution,180)};if(item.file_id)updated.push(item)}return updated}
async function registrySpreadsheet(){let id=clean(process.env.GOOGLE_SHEETS_SPREADSHEET_ID,120)||await setting('certificates_spreadsheet_id');if(id){await saveSetting('certificates_spreadsheet_id',id);return id}const sheets=await gs(),created=await sheets.spreadsheets.create({requestBody:{properties:{title:'Registro de certificados DPEA'},sheets:[{properties:{title:'Hoja 1'}}]}});id=created.data.spreadsheetId;await (await gd()).files.update({fileId:id,addParents:env('GOOGLE_DRIVE_ROOT_FOLDER_ID'),fields:'id',supportsAllDrives:true});await saveSetting('certificates_spreadsheet_id',id);return id}
function tabName(c){return clean(c.title,80).replace(/[\\/:*?\[\]]/g,'-')||'Curso'}
const sheetHeaders=['Código QR','Nombre completo','C.I.','Evento / curso','Carga horaria','Fecha emisión','Enlace del certificado','Fecha de finalización'];
const quotedSheet=title=>`'${title.replace(/'/g,"''")}'`;
async function ensureSheetHeaders(spreadsheetId,title,sheets){const range=`${quotedSheet(title)}!A1:H1`;await sheets.spreadsheets.values.update({spreadsheetId,range,valueInputOption:'RAW',requestBody:{values:[sheetHeaders]}})}
async function homeSheet(spreadsheetId){const sheets=await gs(),book=await sheets.spreadsheets.get({spreadsheetId,fields:'sheets.properties'}),preferred=clean(process.env.GOOGLE_SHEETS_HOME_SHEET||'Hoja 1',100),available=(book.data.sheets||[]).map(x=>x.properties.title);let title=available.includes(preferred)?preferred:available.find(x=>['Hoja 1','INICIO'].includes(x));if(!title){title=preferred;await sheets.spreadsheets.batchUpdate({spreadsheetId,requestBody:{requests:[{addSheet:{properties:{title}}}]}})}await ensureSheetHeaders(spreadsheetId,title,sheets);return{title,sheets}}
async function registryTab(c){const spreadsheetId=await registrySpreadsheet(),sheets=await gs(),book=await sheets.spreadsheets.get({spreadsheetId,fields:'sheets.properties'}),used=(book.data.sheets||[]).map(x=>x.properties.title);let title=c.spreadsheet_tab_name||tabName(c);if(!c.spreadsheet_tab_name&&used.includes(title))title=`${title.slice(0,70)}-${c.id.slice(0,6)}`;if(!used.includes(title))await sheets.spreadsheets.batchUpdate({spreadsheetId,requestBody:{requests:[{addSheet:{properties:{title}}}]}});await ensureSheetHeaders(spreadsheetId,title,sheets);const meta=await courseMeta(c.id);meta.spreadsheet_tab_name=title;await saveCourseMeta(c.id,meta);c.spreadsheet_tab_name=title;return{spreadsheetId,title}}
async function upsertSheetRecord(sheets,spreadsheetId,title,record){const range=`${quotedSheet(title)}!A:H`,result=await sheets.spreadsheets.values.get({spreadsheetId,range}),values=result.data.values||[],row=values.findIndex((x,i)=>i>0&&x[0]===record[0]);if(row>0)await sheets.spreadsheets.values.update({spreadsheetId,range:`${quotedSheet(title)}!A${row+1}:H${row+1}`,valueInputOption:'USER_ENTERED',requestBody:{values:[record]}});else await sheets.spreadsheets.values.append({spreadsheetId,range,valueInputOption:'USER_ENTERED',insertDataOption:'INSERT_ROWS',requestBody:{values:[record]}})}
async function removeSheetRecord(certificateCode,courseTitle){try{const spreadsheetId=await registrySpreadsheet(),sheets=await gs(),home=await homeSheet(spreadsheetId),tabs=[home.title];if(courseTitle){const c=await findCourse(courseTitle);if(c?.spreadsheet_tab_name)tabs.push(c.spreadsheet_tab_name)}for(const title of [...new Set(tabs)]){const range=`${quotedSheet(title)}!A:H`,result=await sheets.spreadsheets.values.get({spreadsheetId,range}),values=result.data.values||[],row=values.findIndex((x,i)=>i>0&&x[0]===certificateCode);if(row>0)await sheets.spreadsheets.values.clear({spreadsheetId,range:`${quotedSheet(title)}!A${row+1}:H${row+1}`})}}catch(e){console.warn('No se pudo retirar el certificado de Google Sheets:',e.message)}}
async function syncSheet(cert,c){const spreadsheetId=await registrySpreadsheet(),link=`https://drive.google.com/file/d/${cert.drive_file_id}/view`,record=[cert.code,cert.full_name,cert.document_id||'',c.title,cert.hours||'',cert.issue_date||'',link,c.end_date||''],home=await homeSheet(spreadsheetId);await upsertSheetRecord(home.sheets,spreadsheetId,home.title,record);const courseTab=await registryTab(c);await ensureSheetHeaders(spreadsheetId,courseTab.title,home.sheets);await upsertSheetRecord(home.sheets,spreadsheetId,courseTab.title,record)}
function wrap(text,font,size,width){const out=[];let line='';for(const word of String(text||'').split(/\s+/)){const next=line?`${line} ${word}`:word;if(font.widthOfTextAtSize(next,size)<=width)line=next;else{if(line)out.push(line);line=word}}if(line)out.push(line);return out}
async function pdf(cert,c,url,background=null,signatures=[]){
 const d=await PDFDocument.create(),p=d.addPage([842,595]),regular=await d.embedFont(StandardFonts.Helvetica),bold=await d.embedFont(StandardFonts.HelveticaBold),display=await d.embedFont(StandardFonts.TimesRomanBoldItalic),blue=rgb(0,79/255,159/255),red=rgb(227/255,6/255,19/255);
 if(background){try{const image=c.template_name?.toLowerCase().endsWith('.png')?await d.embedPng(background):await d.embedJpg(background);p.drawImage(image,{x:0,y:0,width:842,height:595})}catch(e){console.warn('Plantilla inválida:',e.message)}}else{p.drawRectangle({x:18,y:18,width:806,height:559,borderColor:blue,borderWidth:5});p.drawRectangle({x:29,y:29,width:784,height:537,borderColor:red,borderWidth:1})}
 const center=(text,y,size,font=regular,color=rgb(.1,.1,.1),maxWidth=700)=>{text=String(text||'');while(font.widthOfTextAtSize(text,size)>maxWidth&&size>8)size-=.5;p.drawText(text,{x:(842-font.widthOfTextAtSize(text,size))/2,y,size,font,color})};
 const block=(text,x,y,size,font=regular,width=130)=>{text=String(text||'');while(font.widthOfTextAtSize(text,size)>width&&size>7)size-=.5;p.drawText(text,{x:x+(width-font.widthOfTextAtSize(text,size))/2,y,size,font,color:rgb(.12,.15,.2)})};
 if(!background){const seal=path.join(ROOT,'public','emblema-usfx.png');if(fs.existsSync(seal))p.drawImage(await d.embedPng(fs.readFileSync(seal)),{x:52,y:524,width:44,height:56});center('UNIVERSIDAD MAYOR REAL Y PONTIFICIA DE SAN FRANCISCO XAVIER DE CHUQUISACA',504,12,bold,blue,610);center('VICERRECTORADO',480,21,bold,blue,570);center('DEPARTAMENTO DE PLANIFICACIÓN Y EVALUACIÓN ACADÉMICA',456,14,bold,blue,650);center('CERTIFICADO',400,34,bold,red)}
 center('Se otorga el presente certificado a:',376,16);center(cert.full_name.toUpperCase(),326,29,display,blue,650);center(`Por su participación en: ${c.title}`,276,16,bold);
 const lines=wrap(c.description,regular,12,620).slice(0,4);lines.forEach((line,i)=>center(line,238-i*17,12,regular,rgb(.25,.28,.34),620));const y=signatures.length?Math.max(151,210-lines.length*17):Math.max(134,210-lines.length*17);if(cert.hours)center(`Carga horaria: ${cert.hours}`,y,12);center(`Fecha de emisión: ${cert.issue_date}`,y-25,12);
 const q=await d.embedPng(Buffer.from((await QRCode.toDataURL(url,{width:500,margin:2,errorCorrectionLevel:'H'})).split(',')[1],'base64')),qx=689,qy=425;p.drawImage(q,{x:qx,y:qy,width:105,height:105});const emblemPath=path.join(ROOT,'public','emblema-usfx.png');if(fs.existsSync(emblemPath)){const emblem=await d.embedPng(fs.readFileSync(emblemPath));p.drawRectangle({x:qx+38,y:qy+36,width:29,height:33,color:rgb(1,1,1)});p.drawImage(emblem,{x:qx+42,y:qy+38,width:21,height:29})}
 if(signatures.length){const area=700,width=area/signatures.length;for(let i=0;i<signatures.length;i++){const s=signatures[i],x=71+i*width;try{const image=await d.embedPng(s.image),scaled=image.scaleToFit(Math.min(105,width-20),40);p.drawImage(image,{x:x+(width-scaled.width)/2,y:75,width:scaled.width,height:scaled.height})}catch(e){console.warn('Firma inválida:',e.message)}block(s.name,x,61,10,bold,width);block(s.role,x,48,8.5,regular,width);block(s.institution,x,35,8.5,regular,width)}}
 return Buffer.from(await d.save())
}
async function uploadPdf(cert,c,base){const api=await gd(),background=await templateBuffer(c.template_file_id),assets=await signatureAssets(c.signatures),buffer=await pdf(cert,c,verificationLink(base,cert.code),background,assets),name=`${cert.full_name} - ${c.title}.pdf`.replace(/[\\/:*?"<>|]/g,'-');let id=cert.drive_file_id;if(id)await api.files.update({fileId:id,media:{mimeType:'application/pdf',body:Readable.from(buffer)},requestBody:{name},supportsAllDrives:true});else id=(await api.files.create({requestBody:{name,parents:[await folder(c)]},media:{mimeType:'application/pdf',body:Readable.from(buffer)},fields:'id',supportsAllDrives:true})).data.id;cert.drive_file_id=id;return cert}
async function createPrimary(x,c,base){const{data:existing,error:checkError}=await db().from('certificates').select('id').eq('code',x.code).maybeSingle();if(checkError)throw checkError;if(existing)throw Error('No se pudo generar un código único. Intente crear el certificado nuevamente.');const cert={code:x.code,full_name:x.full_name,document_id:x.document_id,hours:x.hours,issue_date:x.issue_date};await uploadPdf(cert,c,base);await syncSheet(cert,c);const{data,error}=await db().from('certificates').insert({code:cert.code,full_name:cert.full_name,document_id:cert.document_id,course_id:c.id,hours:cert.hours,issue_date:cert.issue_date,drive_file_id:cert.drive_file_id}).select().single();if(error)throw error;return data}
async function store(cert,c,base){await uploadPdf(cert,c,base);await syncSheet(cert,c);const{error}=await db().from('certificates').update({drive_file_id:cert.drive_file_id}).eq('id',cert.id);if(error)throw error}
const row=o=>{const k=Object.fromEntries(Object.entries(o).map(([a,v])=>[a.trim().toLowerCase(),v]));return{code:clean(k.codigo||k.code||code(),80).toUpperCase(),full_name:clean(k.nombre||k.participante,250),document_id:clean(k.ci||k.documento,80),course_title:clean(k.curso||k.evento,250),course_description:clean(k.descripcion||k.description,2500),template_file_id:clean(k.template_file_id,250),template_name:clean(k.template_name,250),end_date:clean(k.fecha_fin||k['fecha de finalización']||k.fecha_finalizacion,30),hours:clean(k.horas||k['carga horaria'],80),issue_date:clean(k.fecha||new Date().toISOString().slice(0,10),30)}};
app.get('/',(_q,res)=>res.render('home'));app.get('/salud',async(_q,res)=>{try{const{error}=await db().from('courses').select('id').limit(1);if(error)throw error;res.json({ok:true,service:'certificates'})}catch(e){console.error('Comprobación de Supabase falló:',e.message);res.status(503).json({ok:false})}});app.get('/buscar',(req,res)=>res.redirect(req.query.codigo?`/verificar/${encodeURIComponent(clean(req.query.codigo,80))}`:'/'));
app.get('/verificar/:code',async(req,res,next)=>{try{const{data,error}=await db().from('certificates').select('*,courses(*)').ilike('code',clean(req.params.code,80)).maybeSingle();if(error)throw error;res.status(data?200:404).render('verify',{cert:data})}catch(e){next(e)}});
app.get('/certificados/:code/pdf',async(req,res,next)=>{try{const{data:cert,error}=await db().from('certificates').select('drive_file_id,code,status').ilike('code',clean(req.params.code,80)).maybeSingle();if(error)throw error;if(!cert||cert.status!=='VALIDO'||!cert.drive_file_id)return res.sendStatus(404);const file=await (await gd()).files.get({fileId:cert.drive_file_id,alt:'media',supportsAllDrives:true},{responseType:'stream'});res.set({'Content-Type':'application/pdf','Content-Disposition':`inline; filename="${cert.code}.pdf"`});file.data.pipe(res)}catch(e){next(e)}});
app.get('/admin/login',(_q,res)=>res.render('login',{error:null}));app.post('/admin/login',(req,res)=>{if(clean(req.body.username,100)!==env('ADMIN_USER')||clean(req.body.password,300)!==env('ADMIN_PASSWORD'))return res.status(401).render('login',{error:'Usuario o contraseña incorrectos.'});req.session.user=req.body.username;res.redirect('/admin')});app.post('/admin/logout',auth,(req,res)=>{req.session=null;res.redirect('/')});
app.get('/admin',auth,async(req,res,next)=>{try{let query=db().from('certificates').select('*,courses(id,title,drive_folder_id)').order('created_at',{ascending:false}).limit(500),search=clean(req.query.q,200);if(search)query=query.or(`code.ilike.%${search}%,full_name.ilike.%${search}%`);const[{data,error},{count:total},{count:validos},{count:anulados}]=await Promise.all([query,db().from('certificates').select('*',{count:'exact',head:true}),db().from('certificates').select('*',{count:'exact',head:true}).eq('status','VALIDO'),db().from('certificates').select('*',{count:'exact',head:true}).eq('status','ANULADO')]);if(error)throw error;const groups=Object.values((data||[]).reduce((all,cert)=>{const title=cert.courses?.title||'Sin curso';(all[title]??={id:cert.courses?.id,title,folderId:cert.courses?.drive_folder_id,certs:[]}).certs.push(cert);return all},{}));res.render('admin',{certs:data||[],groups,q:search,stats:{total,validos,anulados}})}catch(e){next(e)}});
app.get('/admin/actividad',auth,async(_req,res,next)=>{try{const{data,error}=await db().from('activity_log').select('*').order('created_at',{ascending:false}).limit(300);if(error)throw error;res.render('activity',{entries:data||[]})}catch(e){next(e)}});
app.get('/admin/nuevo',auth,async(_req,res,next)=>{try{res.render('form',{cert:null,courses:await courses(),templates:await safeTemplates(),error:null})}catch(e){next(e)}});
app.post('/admin/nuevo',auth,signatureUpload.fields([{name:'firma_1',maxCount:1},{name:'firma_2',maxCount:1},{name:'firma_3',maxCount:1},{name:'firma_4',maxCount:1},{name:'firma_5',maxCount:1}]),async(req,res,next)=>{const x=row(req.body);try{if(!x.full_name||!x.course_title)throw Error('Nombre y curso son obligatorios');const previous=await findCourse(x.course_title),courseSignatures=await buildCourseSignatures(req,previous?.signatures||[]),c=await course(x.course_title,x.course_description,x.template_file_id,x.template_name,x.end_date,true,courseSignatures),cert=await createPrimary(x,c,res.locals.baseUrl);await activity(req,'Certificado creado',{certificate_id:cert.id,code:cert.code,course:c.title});req.session.message=`Certificado ${cert.code} guardado primero en Google Sheets y después en Supabase.`;res.redirect('/admin')}catch(e){try{res.status(400).render('form',{cert:x,courses:await courses(),templates:await safeTemplates(),error:e.message})}catch(z){next(z)}}});
app.get('/admin/plantillas',auth,async(_req,res,next)=>{try{res.render('templates',{templates:await templates(),folderId:await templatesFolder(),error:null})}catch(e){res.status(500).render('templates',{templates:[],folderId:null,error:e.message})}});
app.post('/admin/plantillas',auth,templateUpload.single('plantilla'),async(req,res,next)=>{try{if(!req.file)throw Error('Seleccione una imagen PNG o JPG.');const api=await gd(),file=await api.files.create({requestBody:{name:clean(req.file.originalname,200),parents:[await templatesFolder()]},media:{mimeType:req.file.mimetype,body:Readable.from(req.file.buffer)},fields:'id,name',supportsAllDrives:true});await activity(req,'Plantilla subida',{file_id:file.data.id,name:file.data.name});req.session.message='Plantilla guardada en Drive.';res.redirect('/admin/plantillas')}catch(e){next(e)}});
app.post('/admin/plantillas/:id/eliminar',auth,async(req,res,next)=>{try{await trashDriveFile(req.params.id);await activity(req,'Plantilla eliminada',{file_id:req.params.id});req.session.message='Plantilla enviada a la papelera de Drive. Seleccione otra plantilla al editar los cursos que la usaban.';res.redirect('/admin/plantillas')}catch(e){next(e)}});
app.get('/admin/:id/editar',auth,async(req,res,next)=>{try{const{data,error}=await db().from('certificates').select('*,courses(*)').eq('id',req.params.id).maybeSingle();if(error)throw error;if(!data)return res.sendStatus(404);data.courses=await withCourseMeta(data.courses);res.render('form',{cert:data,courses:await courses(),templates:await safeTemplates(),error:null})}catch(e){next(e)}});
app.post('/admin/:id/editar',auth,signatureUpload.fields([{name:'firma_1',maxCount:1},{name:'firma_2',maxCount:1},{name:'firma_3',maxCount:1},{name:'firma_4',maxCount:1},{name:'firma_5',maxCount:1}]),async(req,res,next)=>{try{const x=row(req.body),previous=await findCourse(x.course_title),courseSignatures=await buildCourseSignatures(req,previous?.signatures||[]),c=await course(x.course_title,x.course_description,x.template_file_id,x.template_name,x.end_date,true,courseSignatures),{data:old}=await db().from('certificates').select('*').eq('id',req.params.id).single();x.code=old?.code||x.code;const{data:cert,error}=await db().from('certificates').update({code:x.code,full_name:x.full_name,document_id:x.document_id,course_id:c.id,hours:x.hours,issue_date:x.issue_date,status:req.body.status==='ANULADO'?'ANULADO':'VALIDO'}).eq('id',req.params.id).select().single();if(error)throw error;cert.drive_file_id=old?.drive_file_id;await store(cert,c,res.locals.baseUrl);await activity(req,'Certificado actualizado',{certificate_id:cert.id,code:cert.code,course:c.title});req.session.message='Certificado, Drive y Google Sheets actualizados.';res.redirect('/admin')}catch(e){next(e)}});
app.post('/admin/:id/estado',auth,async(req,res,next)=>{try{const status=req.body.status==='ANULADO'?'ANULADO':'VALIDO',{data:cert,error}=await db().from('certificates').update({status}).eq('id',req.params.id).select('id,code').single();if(error)throw error;await activity(req,'Estado de certificado actualizado',{certificate_id:cert.id,code:cert.code,status});req.session.message=`Estado cambiado a ${status}.`;res.redirect('/admin')}catch(e){next(e)}});
app.post('/admin/:id/eliminar',auth,async(req,res,next)=>{try{const{data:cert,error:readError}=await db().from('certificates').select('*,courses(title)').eq('id',req.params.id).maybeSingle();if(readError)throw readError;if(!cert)return res.sendStatus(404);await trashDriveFile(cert.drive_file_id);await removeSheetRecord(cert.code,cert.courses?.title);const{error}=await db().from('certificates').delete().eq('id',cert.id);if(error)throw error;await activity(req,'Certificado eliminado',{certificate_id:cert.id,code:cert.code,course:cert.courses?.title||'',drive_file_id:cert.drive_file_id||null});req.session.message=`Certificado ${cert.code} eliminado. El PDF fue enviado a la papelera de Drive.`;res.redirect('/admin')}catch(e){next(e)}});
app.get('/admin/cursos/:id/reporte',auth,async(req,res,next)=>{try{const{data:courseData,error:courseError}=await db().from('courses').select('*').eq('id',req.params.id).maybeSingle();if(courseError)throw courseError;if(!courseData)return res.sendStatus(404);const{data:certs,error}=await db().from('certificates').select('*').eq('course_id',courseData.id).order('created_at',{ascending:false});if(error)throw error;const report={course:await withCourseMeta(courseData),certs:certs||[],total:(certs||[]).length,validos:(certs||[]).filter(c=>c.status==='VALIDO').length,anulados:(certs||[]).filter(c=>c.status==='ANULADO').length};res.render('report',report)}catch(e){next(e)}});
app.get('/admin/cursos/:id/reporte.csv',auth,async(req,res,next)=>{try{const{data:courseData,error:courseError}=await db().from('courses').select('*').eq('id',req.params.id).maybeSingle();if(courseError)throw courseError;if(!courseData)return res.sendStatus(404);const{data:certs,error}=await db().from('certificates').select('*').eq('course_id',courseData.id).order('created_at');if(error)throw error;const esc=v=>`"${String(v??'').replace(/"/g,'""')}"`;const reportRows=(certs||[]).map(c=>[c.code,c.full_name,c.document_id,c.hours,c.issue_date,c.status,c.drive_file_id?`https://drive.google.com/file/d/${c.drive_file_id}/view`:'']);const lines=[['Código','Nombre completo','C.I.','Carga horaria','Fecha de emisión','Estado','Enlace PDF'],...reportRows].map(r=>r.map(esc).join(','));res.type('text/csv').attachment(`reporte-${tabName(courseData)}.csv`).send('\uFEFF'+lines.join('\n'))}catch(e){next(e)}});
app.get('/admin/importar',auth,(_q,res)=>res.render('import',{result:null,error:null}));app.post('/admin/importar',auth,upload.single('archivo'),async(req,res,next)=>{if(!req.file)return res.status(400).render('import',{result:null,error:'Seleccione un archivo Excel (.xlsx) o CSV.'});try{const ext=path.extname(req.file.originalname).toLowerCase();let rows;if(ext==='.xlsx'){const book=XLSX.readFile(req.file.path,{raw:false});const first=book.SheetNames[0];rows=XLSX.utils.sheet_to_json(book.Sheets[first],{defval:'',raw:false})}else rows=parse(fs.readFileSync(req.file.path),{columns:true,skip_empty_lines:true,trim:true,bom:true});fs.unlinkSync(req.file.path);let created=0,skipped=0;for(const raw of rows){try{const x=row(raw);if(!x.full_name||!x.course_title)throw Error();const c=await course(x.course_title,x.course_description,'','',x.end_date);const cert=await createPrimary(x,c,res.locals.baseUrl);await activity(req,'Certificado creado por importación',{certificate_id:cert.id,code:cert.code,course:c.title});created++}catch(_e){skipped++}}res.render('import',{result:{total:rows.length,created,skipped},error:null})}catch(e){if(req.file&&fs.existsSync(req.file.path))fs.unlinkSync(req.file.path);next(e)}});
app.get('/admin/plantilla.csv',auth,(_q,res)=>res.type('text/csv').attachment('plantilla-certificados.csv').send('\uFEFFcodigo,nombre,ci,curso,descripcion,horas,fecha,fecha_fin\n,Nombre completo,1234567,Nombre del curso,Descripción común,,2026-09-03,2026-10-03\n'));
app.get('/admin/plantilla.xlsx',auth,(_q,res)=>{const book=XLSX.utils.book_new(),sheet=XLSX.utils.aoa_to_sheet([['codigo','nombre','ci','curso','descripcion','horas','fecha','fecha_fin'],['','Nombre completo','1234567','Nombre del curso','Descripción común','','2026-09-03','2026-10-03']]);sheet['!cols']=[{wch:22},{wch:35},{wch:16},{wch:35},{wch:55},{wch:24},{wch:16},{wch:18}];XLSX.utils.book_append_sheet(book,sheet,'Certificados');const output=XLSX.write(book,{type:'buffer',bookType:'xlsx'});res.type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet').attachment('plantilla-certificados.xlsx').send(output)});
app.use((_q,res)=>res.status(404).render('404'));app.use((e,_q,res,_next)=>{console.error(e);res.status(500).send(process.env.NODE_ENV==='production'?'Ocurrió un error interno.':e.message)});
if(require.main===module){const server=app.listen(Number(process.env.PORT||3000),()=>console.log(`Sistema DPEA disponible en http://localhost:${process.env.PORT||3000}`));server.on('error',e=>{console.error('No se pudo iniciar el servidor:',e.message);process.exitCode=1})}
module.exports=app;module.exports.generateCertificatePdf=pdf;


