require('dotenv').config();
const path=require('path'),fs=require('fs'),crypto=require('crypto');
const express=require('express'),cookieSession=require('cookie-session'),helmet=require('helmet'),multer=require('multer');
const QRCode=require('qrcode'),{parse}=require('csv-parse/sync'),{PDFDocument,StandardFonts,rgb}=require('pdf-lib');
const {createClient}=require('@supabase/supabase-js'),{google}=require('googleapis'),{Readable}=require('stream');
const app=express(),ROOT=__dirname,TMP=path.join(ROOT,'storage','imports'); fs.mkdirSync(TMP,{recursive:true});
const upload=multer({dest:TMP,limits:{fileSize:5e6},fileFilter:(_r,f,cb)=>cb(null,/\.csv$/i.test(f.originalname))});
const env=n=>{if(!process.env[n])throw new Error(`Falta la variable ${n}`);return process.env[n]};
const db=()=>createClient(env('SUPABASE_URL'),env('SUPABASE_SERVICE_ROLE_KEY'),{auth:{persistSession:false}});
const gd=()=>google.drive({version:'v3',auth:new google.auth.JWT({email:env('GOOGLE_SERVICE_ACCOUNT_EMAIL'),key:env('GOOGLE_PRIVATE_KEY').replace(/\\n/g,'\n'),scopes:['https://www.googleapis.com/auth/drive']})});
const clean=(v,n=500)=>String(v??'').trim().slice(0,n),code=()=>`DPEA-${new Date().getFullYear()}-${crypto.randomBytes(6).toString('hex').toUpperCase()}`;
app.set('view engine','ejs');app.set('views',path.join(ROOT,'views'));app.set('trust proxy',1);
app.use(helmet({contentSecurityPolicy:false}),express.urlencoded({extended:false}),express.json(),express.static(path.join(ROOT,'public')));
app.use(cookieSession({name:'dpea_session',keys:[process.env.SESSION_SECRET||'cambiar'],httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:28800000}));
app.use((req,res,next)=>{res.locals.institution=process.env.INSTITUTION_NAME||'División de Planificación y Evaluación Académica';res.locals.officialUrl=process.env.OFFICIAL_URL||'https://planificacionacademica.usfx.bo/';res.locals.baseUrl=(process.env.BASE_URL||`${req.protocol}://${req.get('host')}`).replace(/\/$/,'');res.locals.user=req.session?.user||null;res.locals.message=req.session?.message||null;if(req.session)delete req.session.message;next()});
const auth=(req,res,next)=>req.session?.user?next():res.redirect('/admin/login');
async function courses(){const{data,error}=await db().from('courses').select('*').order('title');if(error)throw error;return data||[]}
async function course(title,description=''){title=clean(title,250);description=clean(description,2500);if(!title)throw Error('El curso es obligatorio');const c=db();let{data,error}=await c.from('courses').select('*').ilike('title',title).maybeSingle();if(error)throw error;if(data){if(description&&description!==data.description){({data,error}=await c.from('courses').update({description}).eq('id',data.id).select().single());if(error)throw error}return data}({data,error}=await c.from('courses').insert({title,description}).select().single());if(error)throw error;return data}
async function folder(c){if(c.drive_folder_id)return c.drive_folder_id;const api=gd(),root=env('GOOGLE_DRIVE_ROOT_FOLDER_ID'),name=clean(c.title,100).replace(/[\\/:*?"<>|]/g,'-'),q=name.replace(/'/g,"\\'");const found=await api.files.list({q:`'${root}' in parents and name='${q}' and mimeType='application/vnd.google-apps.folder' and trashed=false`,fields:'files(id)',supportsAllDrives:true,includeItemsFromAllDrives:true});let id=found.data.files?.[0]?.id;if(!id)id=(await api.files.create({requestBody:{name,mimeType:'application/vnd.google-apps.folder',parents:[root]},fields:'id',supportsAllDrives:true})).data.id;const{error}=await db().from('courses').update({drive_folder_id:id}).eq('id',c.id);if(error)throw error;return id}
function wrap(text,font,size,width){const out=[];let line='';for(const w of String(text||'').split(/\s+/)){const t=line?`${line} ${w}`:w;if(font.widthOfTextAtSize(t,size)<=width)line=t;else{if(line)out.push(line);line=w}}if(line)out.push(line);return out}
async function pdf(cert,c,url){const d=await PDFDocument.create(),p=d.addPage([842,595]),r=await d.embedFont(StandardFonts.Helvetica),b=await d.embedFont(StandardFonts.HelveticaBold),display=await d.embedFont(StandardFonts.TimesRomanBoldItalic),blue=rgb(0,79/255,159/255),red=rgb(227/255,6/255,19/255);p.drawRectangle({x:18,y:18,width:806,height:559,borderColor:blue,borderWidth:5});p.drawRectangle({x:29,y:29,width:784,height:537,borderColor:red,borderWidth:1});const center=(t,y,s,f=r,col=rgb(.1,.1,.1),mw=700)=>{while(f.widthOfTextAtSize(t,s)>mw&&s>10)s-=.5;p.drawText(t,{x:(842-f.widthOfTextAtSize(t,s))/2,y,size:s,font:f,color:col})};const logo=path.join(ROOT,'public','logo-dpea.png');if(fs.existsSync(logo))p.drawImage(await d.embedPng(fs.readFileSync(logo)),{x:48,y:482,width:112,height:49});center('UNIVERSIDAD MAYOR, REAL Y PONTIFICIA DE SAN FRANCISCO XAVIER',525,13,b,blue,580);center('DIVISIÓN DE PLANIFICACIÓN Y EVALUACIÓN ACADÉMICA',498,15,b,blue,570);center('CERTIFICADO',421,34,b,red);center('Se otorga el presente certificado a:',376,16);center(cert.full_name.toUpperCase(),326,29,display,blue,650);center(`Por su participación en: ${c.title}`,276,16,b);const lines=wrap(c.description,r,12,620).slice(0,4);lines.forEach((x,i)=>center(x,238-i*17,12,r,rgb(.25,.28,.34),620));const y=Math.max(134,210-lines.length*17);if(cert.hours)center(`Carga horaria: ${cert.hours}`,y,12);center(`Fecha de emisión: ${cert.issue_date}`,y-25,12);const q=await d.embedPng(Buffer.from((await QRCode.toDataURL(url,{width:500,margin:1,errorCorrectionLevel:'H'})).split(',')[1],'base64'));p.drawImage(q,{x:689,y:425,width:105,height:105});return Buffer.from(await d.save())}
async function store(cert,c,base){const api=gd(),buf=await pdf(cert,c,`${base}/verificar/${encodeURIComponent(cert.code)}`),name=`${cert.full_name} - ${c.title}.pdf`.replace(/[\\/:*?"<>|]/g,'-');let id=cert.drive_file_id;if(id)await api.files.update({fileId:id,media:{mimeType:'application/pdf',body:Readable.from(buf)},requestBody:{name},supportsAllDrives:true});else id=(await api.files.create({requestBody:{name,parents:[await folder(c)]},media:{mimeType:'application/pdf',body:Readable.from(buf)},fields:'id',supportsAllDrives:true})).data.id;const{error}=await db().from('certificates').update({drive_file_id:id}).eq('id',cert.id);if(error)throw error}
const row=o=>{const k=Object.fromEntries(Object.entries(o).map(([a,v])=>[a.trim().toLowerCase(),v]));return{code:clean(k.codigo||k.code||code(),80).toUpperCase(),full_name:clean(k.nombre||k.participante,250),document_id:clean(k.ci||k.documento,80),course_title:clean(k.curso||k.evento,250),course_description:clean(k.descripcion||k.description,2500),hours:clean(k.horas||k['carga horaria'],80),issue_date:clean(k.fecha||new Date().toISOString().slice(0,10),30)}};
app.get('/',(_q,s)=>s.render('home'));app.get('/salud',(_q,s)=>s.json({ok:true}));app.get('/buscar',(q,s)=>s.redirect(q.query.codigo?`/verificar/${encodeURIComponent(clean(q.query.codigo,80))}`:'/'));
app.get('/verificar/:code',async(q,s,n)=>{try{const{data,error}=await db().from('certificates').select('*,courses(*)').ilike('code',clean(q.params.code,80)).maybeSingle();if(error)throw error;s.status(data?200:404).render('verify',{cert:data})}catch(e){n(e)}});
app.get('/certificados/:code/pdf',async(q,s,n)=>{try{const{data:c,error}=await db().from('certificates').select('drive_file_id,code,status').ilike('code',clean(q.params.code,80)).maybeSingle();if(error)throw error;if(!c||c.status!=='VALIDO'||!c.drive_file_id)return s.sendStatus(404);const x=await gd().files.get({fileId:c.drive_file_id,alt:'media',supportsAllDrives:true},{responseType:'stream'});s.set({'Content-Type':'application/pdf','Content-Disposition':`inline; filename="${c.code}.pdf"`});x.data.pipe(s)}catch(e){n(e)}});
app.get('/admin/login',(_q,s)=>s.render('login',{error:null}));app.post('/admin/login',(q,s)=>{if(clean(q.body.username,100)!==env('ADMIN_USER')||clean(q.body.password,300)!==env('ADMIN_PASSWORD'))return s.status(401).render('login',{error:'Usuario o contraseña incorrectos.'});q.session.user=q.body.username;s.redirect('/admin')});app.post('/admin/logout',auth,(q,s)=>{q.session=null;s.redirect('/')});
app.get('/admin',auth,async(q,s,n)=>{try{let query=db().from('certificates').select('*,courses(title)').order('created_at',{ascending:false}).limit(500),search=clean(q.query.q,200);if(search)query=query.or(`code.ilike.%${search}%,full_name.ilike.%${search}%`);const[{data,error},{count:total},{count:validos},{count:anulados}]=await Promise.all([query,db().from('certificates').select('*',{count:'exact',head:true}),db().from('certificates').select('*',{count:'exact',head:true}).eq('status','VALIDO'),db().from('certificates').select('*',{count:'exact',head:true}).eq('status','ANULADO')]);if(error)throw error;s.render('admin',{certs:data||[],q:search,stats:{total,validos,anulados}})}catch(e){n(e)}});
app.get('/admin/nuevo',auth,async(_q,s,n)=>{try{s.render('form',{cert:null,courses:await courses(),error:null})}catch(e){n(e)}});
app.post('/admin/nuevo',auth,async(q,s,n)=>{const x=row(q.body);try{if(!x.full_name||!x.course_title)throw Error('Nombre y curso son obligatorios');const c=await course(x.course_title,x.course_description),{data:cert,error}=await db().from('certificates').insert({code:x.code,full_name:x.full_name,document_id:x.document_id,course_id:c.id,hours:x.hours,issue_date:x.issue_date}).select().single();if(error)throw error;await store(cert,c,s.locals.baseUrl);q.session.message=`Certificado ${cert.code} creado y guardado en Drive.`;s.redirect('/admin')}catch(e){try{s.status(400).render('form',{cert:x,courses:await courses(),error:e.message})}catch(z){n(z)}}});
app.get('/admin/:id/editar',auth,async(q,s,n)=>{try{const{data,error}=await db().from('certificates').select('*,courses(*)').eq('id',q.params.id).maybeSingle();if(error)throw error;if(!data)return s.sendStatus(404);s.render('form',{cert:data,courses:await courses(),error:null})}catch(e){n(e)}});
app.post('/admin/:id/editar',auth,async(q,s,n)=>{try{const x=row(q.body),c=await course(x.course_title,x.course_description),{data:old}=await db().from('certificates').select('*').eq('id',q.params.id).single(),{data:cert,error}=await db().from('certificates').update({code:x.code,full_name:x.full_name,document_id:x.document_id,course_id:c.id,hours:x.hours,issue_date:x.issue_date,status:q.body.status==='ANULADO'?'ANULADO':'VALIDO'}).eq('id',q.params.id).select().single();if(error)throw error;cert.drive_file_id=old?.drive_file_id;await store(cert,c,s.locals.baseUrl);q.session.message='Certificado actualizado en Drive.';s.redirect('/admin')}catch(e){n(e)}});
app.post('/admin/:id/estado',auth,async(q,s,n)=>{try{const status=q.body.status==='ANULADO'?'ANULADO':'VALIDO',{error}=await db().from('certificates').update({status}).eq('id',q.params.id);if(error)throw error;q.session.message=`Estado cambiado a ${status}.`;s.redirect('/admin')}catch(e){n(e)}});
app.get('/admin/importar',auth,(_q,s)=>s.render('import',{result:null,error:null}));app.post('/admin/importar',auth,upload.single('archivo'),async(q,s,n)=>{if(!q.file)return s.status(400).render('import',{result:null,error:'Seleccione un CSV.'});try{const rows=parse(fs.readFileSync(q.file.path),{columns:true,skip_empty_lines:true,trim:true,bom:true});fs.unlinkSync(q.file.path);let created=0,skipped=0;for(const a of rows){try{const x=row(a);if(!x.full_name||!x.course_title)throw Error();const c=await course(x.course_title,x.course_description),{data:cert,error}=await db().from('certificates').insert({code:x.code,full_name:x.full_name,document_id:x.document_id,course_id:c.id,hours:x.hours,issue_date:x.issue_date}).select().single();if(error)throw error;await store(cert,c,s.locals.baseUrl);created++}catch(_e){skipped++}}s.render('import',{result:{total:rows.length,created,skipped},error:null})}catch(e){if(fs.existsSync(q.file.path))fs.unlinkSync(q.file.path);n(e)}});
app.get('/admin/plantilla.csv',auth,(_q,s)=>s.type('text/csv').attachment('plantilla-certificados.csv').send('\uFEFFcodigo,nombre,ci,curso,descripcion,horas,fecha\n,Nombre completo,1234567,Nombre del curso,Descripción común,40 horas académicas,2026-09-03\n'));
app.use((_q,s)=>s.status(404).render('404'));app.use((e,_q,s,_n)=>{console.error(e);s.status(500).send(process.env.NODE_ENV==='production'?'Ocurrió un error interno.':e.message)});
if(require.main===module)app.listen(Number(process.env.PORT||3000),()=>console.log(`Sistema DPEA disponible en http://localhost:${process.env.PORT||3000}`));module.exports=app;module.exports.generateCertificatePdf=pdf;
